name: Cypress Tests

on: [push]


jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: install cypress-run
        run: npm i cypress
      - name: Cypress run
        run: npm run cypress-run
         
